export const styles = {
    // --- Main App Layout ---
    appContainer: {
        display: 'flex',
        flexDirection: 'column' as const,
        height: '100vh',
        backgroundColor: 'var(--background-color)'
    },
    appLayout: {
        display: 'grid',
        gridTemplateColumns: '320px 1fr', // Sidebar and Main Content - Increased sidebar width
        flex: 1,
        overflow: 'hidden'
    },
    mainContentArea: {
        flex: 1,
        overflowY: 'auto' as const,
        padding: '1.5rem',
        display: 'flex',
        flexDirection: 'column' as const,
    },

    // --- TopNavBar ---
    topNav: {
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        padding: '0 1.5rem',
        backgroundColor: 'var(--card-bg-color)',
        boxShadow: '0 2px 4px rgba(0,0,0,0.05)',
        zIndex: 10,
        flexShrink: 0,
        height: '60px'
    },
    topNavBranding: {
        display: 'flex',
        alignItems: 'center',
        gap: '0.75rem',
    },
    topNavTitle: {
        fontSize: '1.3rem',
        color: 'var(--primary-color)',
        fontWeight: 600
    },
    topNavTabs: {
        display: 'flex',
        height: '100%',
    },
    categoryTab: {
        padding: '0 1rem',
        cursor: 'pointer',
        border: 'none',
        background: 'none',
        color: 'var(--text-color)',
        position: 'relative' as const,
        display: 'flex',
        alignItems: 'center',
        height: '100%',
        fontSize: '0.9rem',
        fontWeight: 500,
    },
    categoryTabActive: {
        color: 'var(--primary-color)',
    },
    dropdownMenu: {
        position: 'absolute' as const,
        top: '100%',
        left: 0,
        backgroundColor: 'var(--card-bg-color)',
        borderRadius: '0 0 var(--border-radius) var(--border-radius)',
        boxShadow: 'var(--shadow)',
        zIndex: 20,
        minWidth: '220px',
        maxHeight: 'calc(100vh - 80px)',
        overflowY: 'auto' as const,
        border: '1px solid var(--border-color)',
    },
    moduleLink: {
        display: 'block',
        padding: '0.8rem 1.2rem',
        color: 'var(--text-color)',
        textDecoration: 'none',
        fontSize: '0.9rem',
    },
    moduleLinkHover: {
        backgroundColor: 'var(--background-color)',
        color: 'var(--primary-color)',
    },
    moduleLinkActive: {
        backgroundColor: 'var(--primary-color)',
        color: '#fff',
    },
    topNavActions: {
        display: 'flex',
        alignItems: 'center',
        gap: '0.5rem',
    },
    topNavButton: {
        background: 'transparent',
        color: 'var(--text-color)',
        border: '1px solid var(--border-color)',
        padding: '0.5rem 1rem',
        borderRadius: '8px',
        cursor: 'pointer',
        fontSize: '0.85rem',
        fontWeight: 500,
        transition: 'background-color 0.2s, color 0.2s',
        position: 'relative' as const,
    },
    topNavButtonHover: {
        backgroundColor: 'var(--border-color)',
    },

    // --- Theme Selector ---
    themeSelectorPopover: {
        position: 'absolute' as const,
        top: 'calc(100% + 5px)',
        right: 0,
        backgroundColor: 'var(--card-bg-color)',
        borderRadius: 'var(--border-radius)',
        boxShadow: 'var(--shadow)',
        zIndex: 20,
        width: '280px',
        border: '1px solid var(--border-color)',
        padding: '0.75rem',
    },
    themeSelectorHeader: {
        fontSize: '0.8rem',
        fontWeight: 600,
        color: 'var(--light-text-color)',
        textTransform: 'uppercase' as const,
        letterSpacing: '0.5px',
        margin: '0.5rem 0.25rem',
    },
    themeSelectorGrid: {
        display: 'grid',
        gridTemplateColumns: '1fr 1fr',
        gap: '0.5rem',
    },
    themeItem: {
        display: 'flex',
        alignItems: 'center',
        gap: '0.75rem',
        padding: '0.6rem',
        borderRadius: '8px',
        cursor: 'pointer',
        border: '2px solid transparent',
        transition: 'background-color 0.2s',
    },
    themeItemHover: {
        backgroundColor: 'var(--background-color)',
    },
    themeItemActive: {
        borderColor: 'var(--primary-color)',
    },
    themeSwatch: {
        width: '20px',
        height: '20px',
        borderRadius: '50%',
        flexShrink: 0,
        border: '2px solid var(--border-color)',
    },
    themeName: {
        fontSize: '0.9rem',
    },


    // --- SettingsPanel ---
    settingsPanel: {
        backgroundColor: 'var(--card-bg-color)',
        borderRight: '1px solid var(--border-color)',
        padding: '1.5rem',
        overflowY: 'auto' as const,
        display: 'flex',
        flexDirection: 'column' as const,
    },
    settingsHeader: {
        borderBottom: '1px solid var(--border-color)',
        paddingBottom: '1rem',
        marginBottom: '1rem'
    },
    settingsTitle: {
        fontSize: '1.2rem',
        fontWeight: 600,
        color: 'var(--text-color)',
        margin: 0,
    },
    settingsDescription: {
        fontSize: '0.85rem',
        color: 'var(--light-text-color)',
        marginTop: '0.25rem'
    },
    settingsContent: {
        display: 'flex',
        flexDirection: 'column' as const,
        gap: '1.5rem',
        flex: 1
    },
    settingsFieldset: {
        border: '1px solid var(--border-color)',
        borderRadius: 'var(--border-radius)',
        padding: '1rem 1.2rem 1.2rem',
        margin: 0,
        display: 'flex',
        flexDirection: 'column' as const,
        gap: '1rem'
    },
    settingsLegend: {
        padding: '0 0.5rem',
        fontSize: '0.9rem',
        fontWeight: 600,
        color: 'var(--primary-color)',
    },
    settingControl: {
        display: 'flex',
        flexDirection: 'column' as const,
        gap: '0.5rem',
    },
    settingLabel: {
        fontSize: '0.9rem',
        fontWeight: 500,
        color: 'var(--text-color)',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'space-between'
    },
    settingInput: {
        width: '100%',
        padding: '0.6rem 0.8rem',
        fontSize: '0.9rem',
        border: '1px solid var(--border-color)',
        borderRadius: '8px',
        backgroundColor: 'var(--background-color)',
        color: 'var(--text-color)',
        transition: 'border-color 0.2s, box-shadow 0.2s',
    },
    settingSlider: {
        width: '100%',
    },
    tooltipIcon: {
        cursor: 'help',
        color: 'var(--light-text-color)',
        fontSize: '1.1em',
        position: 'relative' as const,
    },
    settingToggle: {
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'space-between',
        gap: '1rem',
    },
    toggleSwitch: {
        position: 'relative' as const,
        display: 'inline-block',
        width: '44px',
        height: '24px',
    },
    toggleSwitchInput: {
        opacity: 0,
        width: 0,
        height: 0,
    },
    toggleSlider: {
        position: 'absolute' as const,
        cursor: 'pointer',
        top: 0, left: 0, right: 0, bottom: 0,
        backgroundColor: 'var(--border-color)',
        transition: '.4s',
        borderRadius: '24px',
    },
    toggleSliderBefore: {
        position: 'absolute' as const,
        content: '""',
        height: '18px',
        width: '18px',
        left: '3px',
        bottom: '3px',
        backgroundColor: 'white',
        transition: '.4s',
        borderRadius: '50%',
    },
    generationButtons: {
        marginTop: '1.5rem',
        paddingTop: '1.5rem',
        borderTop: '1px solid var(--border-color)',
        display: 'flex',
        flexDirection: 'column' as const,
        gap: '0.75rem',
        flexShrink: 0,
    },
    generateButton: (color) => ({
        backgroundColor: color || 'var(--primary-color)',
        color: '#fff',
        border: 'none',
        padding: '0.8rem',
        borderRadius: '8px',
        cursor: 'pointer',
        fontSize: '0.95rem',
        fontWeight: 600,
        transition: 'opacity 0.2s, transform 0.1s',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        gap: '0.5rem',
    }),
    algorithmicButton: {
        backgroundColor: 'var(--light-text-color)',
        color: 'var(--card-bg-color)',
        border: 'none',
        padding: '0.8rem',
        borderRadius: '8px',
        cursor: 'pointer',
        fontSize: '0.95rem',
        fontWeight: 600,
        transition: 'opacity 0.2s, background-color 0.2s, transform 0.1s',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        gap: '0.5rem',
    },
    
    // --- Workspace ---
    workspace: {
        display: 'flex',
        flexDirection: 'column' as const,
        flex: 1,
    },
    workspaceToolbar: {
        display: 'grid',
        gridTemplateColumns: 'repeat(5, 1fr) auto',
        alignItems: 'center',
        padding: '0.75rem 1rem',
        backgroundColor: 'var(--card-bg-color)',
        border: '1px solid var(--border-color)',
        borderRadius: 'var(--border-radius)',
        marginBottom: '1.5rem',
        gap: '1.5rem',
    },
    toolbarControlGroup: {
        display: 'flex',
        flexDirection: 'column' as const,
        gap: '0.25rem',
    },
    toolbarLabel: {
        fontSize: '0.8rem',
        color: 'var(--light-text-color)',
        display: 'flex',
        alignItems: 'center',
        gap: '0.5rem',
        justifyContent: 'space-between',
    },
    toolbarSlider: {
        width: '100%',
        margin: '0',
    },
    toolbarButtonGroup: {
        display: 'flex',
        borderRadius: '6px',
        overflow: 'hidden',
        border: '1px solid var(--border-color)',
        marginTop: '2px',
    },
    toolbarButton: {
        flex: 1,
        padding: '0.5rem',
        background: 'transparent',
        border: 'none',
        borderRight: '1px solid var(--border-color)',
        cursor: 'pointer',
        fontSize: '1rem',
        color: 'var(--text-color)',
        transition: 'background-color 0.2s',
    },
    toolbarButtonActive: {
        background: 'var(--primary-color)',
        color: 'white',
    },
    toolbarActions: {
        gridColumn: '6 / 7',
        display: 'flex',
        justifyContent: 'flex-end',
        gap: '0.75rem',
    },
    actionButton: {
        backgroundColor: 'transparent',
        color: 'var(--text-color)',
        border: '1px solid var(--border-color)',
        padding: '0.6rem 1.2rem',
        borderRadius: '8px',
        cursor: 'pointer',
        fontSize: '0.9rem',
        fontWeight: 500,
        display: 'flex',
        alignItems: 'center',
        gap: '0.5rem',
    },
    worksheetContainer: {
        flex: 1,
        backgroundColor: 'var(--background-color)',
        display: 'flex',
        justifyContent: 'center',
        padding: '1rem',
        overflowY: 'auto' as const,
    },
    loaderContainer: {
        width: '100%',
        minHeight: '400px',
        textAlign: 'center' as const,
        display: 'flex',
        flexDirection: 'column' as const,
        alignItems: 'center',
        justifyContent: 'center',
        gap: '1rem'
    },
    animatedLoader: {
        display: 'flex',
        gap: '1.5rem',
    },
    loaderIcon: {
        fontSize: '2.5rem',
        animation: 'bounce 1.4s infinite ease-in-out both',
    },
    error: { color: '#e74c3c', textAlign: 'center' as const },
    placeholder: { minHeight: '400px', color: 'var(--light-text-color)', textAlign: 'center' as const, display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: '1rem' },

    // --- Saved/Feedback Shared ---
    pageTitle: {
        fontSize: '1.8rem',
        marginBottom: '1.5rem',
        textAlign: 'center' as const,
        fontWeight: 600
    },
    fullPageWrapper: {
        backgroundColor: 'var(--card-bg-color)',
        borderRadius: 'var(--border-radius)',
        padding: '2rem',
        flex: 1,
    },

    // --- Saved Activities ---
    savedList: {
        display: 'flex',
        flexDirection: 'column' as const,
        gap: '1rem',
    },
    savedItem: {
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        padding: '1rem',
        border: '1px solid var(--border-color)',
        borderRadius: 'var(--border-radius)',
        backgroundColor: 'var(--card-bg-color)',
        transition: 'background-color 0.2s',
    },
    savedItemInfo: {
        display: 'flex',
        alignItems: 'center',
        gap: '1rem',
        cursor: 'pointer',
        flex: 1,
    },
    savedItemIcon: {
        width: '40px',
        height: '40px',
        borderRadius: '50%',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        fontSize: '1.5rem',
        color: '#fff',
        flexShrink: 0
    },
    savedItemTitle: { fontSize: '1rem', fontWeight: 600, margin: 0 },
    savedItemModule: { fontSize: '0.9rem', color: 'var(--light-text-color)', margin: 0 },
    deleteButton: {
        background: '#e74c3c', color: '#fff', border: 'none', padding: '0.5rem 1rem', borderRadius: '6px', cursor: 'pointer', fontSize: '0.8rem',
    },
    navigationHeader: { display: 'flex', alignItems: 'center', marginBottom: '1.5rem', position: 'relative' as const, justifyContent: 'center' as const },
    backButton: {
        position: 'absolute' as const,
        left: '0',
        background: 'none',
        border: '1px solid var(--border-color)',
        padding: '0.5rem 1rem',
        borderRadius: '8px',
        cursor: 'pointer',
        fontSize: '0.9rem',
        color: 'var(--text-color)',
    },
    viewerActions: {
        padding: '1rem',
        border: '1px solid var(--border-color)',
        borderRadius: 'var(--border-radius)',
        marginBottom: '1.5rem',
        textAlign: 'center' as const,
    },
    viewerWorksheet: {
        display: 'flex',
        flexDirection: 'column' as const,
        alignItems: 'center',
        gap: '1.5rem',
    },
    
    // --- Feedback Form ---
    feedbackForm: {
        maxWidth: '600px',
        margin: '0 auto',
        display: 'flex',
        flexDirection: 'column' as const,
        gap: '1rem'
    },
    formGroup: { display: 'flex', flexDirection: 'column' as const, gap: '0.5rem' },
    formInput: { padding: '0.7rem 1rem', border: '1px solid var(--border-color)', borderRadius: '8px', fontSize: '1rem', backgroundColor: 'var(--card-bg-color)', color: 'var(--text-color)' },
    formTextarea: { padding: '0.7rem 1rem', border: '1px solid var(--border-color)', borderRadius: '8px', fontSize: '1rem', backgroundColor: 'var(--card-bg-color)', color: 'var(--text-color)', fontFamily: "'Poppins', sans-serif" },
    formButton: {
        background: 'var(--primary-color)', color: '#fff', border: 'none', padding: '0.7rem 1.5rem', borderRadius: '8px', cursor: 'pointer', fontSize: '1rem', fontWeight: 500,
    },
    formButtonSecondary: {
        background: 'transparent', color: 'var(--text-color)', border: '1px solid var(--border-color)', padding: '0.7rem 1.5rem', borderRadius: '8px', cursor: 'pointer', fontSize: '1rem', marginRight: '1rem',
    },

    // --- Fix: Styles for unused components to fix TypeScript errors ---
    moduleDescriptionContainer: {
        backgroundColor: 'var(--background-color)',
        padding: '1rem 1.5rem',
        borderRadius: 'var(--border-radius)',
        marginBottom: '1.5rem',
        border: '1px solid var(--border-color)',
    },
    moduleDescriptionText: {
        margin: 0,
        color: 'var(--text-color)',
        fontSize: '0.9rem',
        lineHeight: 1.6,
    },
    activityContainer: {
        display: 'grid',
        gridTemplateColumns: '300px 1fr',
        gap: '2rem',
        flex: 1,
    },
    activityControls: {
        backgroundColor: 'var(--card-bg-color)',
        padding: '1.5rem',
        borderRadius: 'var(--border-radius)',
        border: '1px solid var(--border-color)',
        display: 'flex',
        flexDirection: 'column' as const,
        gap: '1.5rem',
    },
    activityDescription: {
        fontSize: '0.9rem',
        color: 'var(--light-text-color)',
        margin: 0,
    },
    generationSetup: {
        display: 'flex',
        flexDirection: 'column' as const,
        gap: '1rem',
    },
    settingItem: {
        display: 'flex',
        flexDirection: 'column' as const,
        gap: '0.5rem',
    },
    numberInput: {
        width: '80px',
        padding: '0.5rem',
        border: '1px solid var(--border-color)',
        borderRadius: '6px',
    },
    hr: {
        border: 'none',
        borderTop: '1px solid var(--border-color)',
        margin: '0',
    },
    postGenerationControls: {
        display: 'flex',
        flexDirection: 'column' as const,
        gap: '0.75rem',
    },
    saveButton: {
        backgroundColor: '#27ae60',
        color: '#fff',
        border: 'none',
        padding: '0.7rem',
        borderRadius: '8px',
        cursor: 'pointer',
        fontSize: '0.9rem',
    },
    printButton: {
        backgroundColor: '#2980b9',
        color: '#fff',
        border: 'none',
        padding: '0.7rem',
        borderRadius: '8px',
        cursor: 'pointer',
        fontSize: '0.9rem',
    },
    worksheet: {
        display: 'grid',
        gap: '1rem',
        alignContent: 'start',
    },
    loaderText: {
        color: 'var(--text-color)',
        fontSize: '1rem',
    },
    appearanceContainer: {
        display: 'flex',
        flexDirection: 'column' as const,
        gap: '1.5rem',
    },
    buttonGroup: {
        display: 'flex',
    },
    buttonGroupButton: {
        flex: 1,
        padding: '0.5rem',
        border: '1px solid var(--border-color)',
        background: 'transparent',
        cursor: 'pointer',
    },
    buttonGroupActive: {
        flex: 1,
        padding: '0.5rem',
        border: '1px solid var(--primary-color)',
        background: 'var(--primary-color)',
        color: '#fff',
        cursor: 'pointer',
    },
    slider: {
        width: '100%',
    },
    cardGrid: {
        display: 'grid',
        gridTemplateColumns: 'repeat(auto-fill, minmax(200px, 1fr))',
        gap: '1.5rem',
    },
    card: {
        backgroundColor: 'var(--card-bg-color)',
        borderRadius: 'var(--border-radius)',
        padding: '1.5rem',
        textAlign: 'center' as const,
        cursor: 'pointer',
        transition: 'transform 0.2s, box-shadow 0.2s',
        border: '1px solid var(--border-color)',
    },
    cardIcon: {
        fontSize: '2.5rem',
    },
    cardTitle: {
        margin: '1rem 0 0 0',
        fontSize: '1.1rem',
        fontWeight: 600,
        color: 'var(--text-color)',
    },
    moduleCard: {
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        minHeight: '100px',
    },
    header: {
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        padding: '1rem 2rem',
        backgroundColor: 'var(--card-bg-color)',
        borderBottom: '1px solid var(--border-color)',
    },
    headerBranding: {
        cursor: 'pointer',
    },
    headerTitle: {
        margin: 0,
        fontSize: '1.5rem',
        color: 'var(--primary-color)',
        fontWeight: 600,
    },
    headerSubtitle: {
        margin: 0,
        color: 'var(--light-text-color)',
    },
    headerNav: {
        display: 'flex',
        gap: '1rem',
    },
    navButton: {
        background: 'transparent',
        color: 'var(--text-color)',
        border: '1px solid var(--border-color)',
        padding: '0.5rem 1rem',
        borderRadius: '8px',
        cursor: 'pointer',
        fontSize: '0.85rem',
        fontWeight: 500,
        transition: 'background-color 0.2s, color 0.2s',
    },
};